2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_setup.py:_flush():76] Configure stats pid to 13402
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_setup.py:_flush():76] Loading settings from /home/huseyin/.config/wandb/settings
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_setup.py:_flush():76] Loading settings from /home/huseyin/fungtion/dannpy_yeniden/DANN_py3/wandb/settings
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/huseyin/fungtion/dannpy_yeniden/DANN_py3/main.py', 'program': 'main.py'}
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_init.py:_log_setup():528] Logging user logs to /home/huseyin/fungtion/dannpy_yeniden/DANN_py3/wandb/run-20240203_021406-n2mlzfsf/logs/debug.log
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_init.py:_log_setup():529] Logging internal logs to /home/huseyin/fungtion/dannpy_yeniden/DANN_py3/wandb/run-20240203_021406-n2mlzfsf/logs/debug-internal.log
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_init.py:init():568] calling init triggers
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'ms': 1.0, 'Mt': 0}
2024-02-03 02:14:06,960 INFO    MainThread:13402 [wandb_init.py:init():618] starting backend
2024-02-03 02:14:06,961 INFO    MainThread:13402 [wandb_init.py:init():622] setting up manager
2024-02-03 02:14:06,962 INFO    MainThread:13402 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-03 02:14:06,962 INFO    MainThread:13402 [wandb_init.py:init():628] backend started and connected
2024-02-03 02:14:06,965 INFO    MainThread:13402 [wandb_init.py:init():720] updated telemetry
2024-02-03 02:14:07,010 INFO    MainThread:13402 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-03 02:15:37,032 ERROR   MainThread:13402 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-03 02:15:37,123 ERROR   MainThread:13402 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/huseyin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/huseyin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-03 02:15:38,126 WARNING MsgRouterThr:13402 [router.py:message_loop():77] message_loop has been closed
